projects/myboard/board/urls.py
from django.urls import path
from . import views

app_name ='board'

#여기는 board에 있는 urls.py다
urlpatterns = [

    # .../board
    path('', views.index, name = 'index'),
    # 글읽기 주소 /board/0
    path('<int:id>/',views.read, name='detail'),
    # 글쓰기 주소
    path('write/',views.write, name='write'),
    # 수정 주소
    path('<int:id>/update/',views.update, name ='update'),
    # 삭제 주소
    path('<int:id>/delete/',views.delete, name ='delete'),

    # #AJAX
    # path('callAjax/',views.call_ajax),
    # 댓글 쓰기 주소
    path('<int:id>/write_reply/',views.write_reply, name = "write_reply"),
    # 댓글 수정 주소
    path('<int:id>/update_reply/',views.update_reply, name = "update_reply"),
    # 댓글 로딩 주소
    path('<int:id>/load_reply/',views.load_reply, name = 'load_reply'),
    # 댓글 삭제 주소
    path('<int:id>/delete_reply/',views.delete_reply, name = "delete_reply"),
    path("<int:id>/download/",views.download, name = "download"),

    # CBV방식으로 호출할 주소 cbv라는 글자가 붙어있으면 호출
    # as_view : 클래스를 view의 기능으로 사용하겠다.
    path('cbv/', views.BoardList.as_view()),
    path('cbv/<int:id>/', views.BoardDetail.as_view()),
]

projects/myboard/myboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings #현재 프로젝트의 settings.py를 의미
from django.conf.urls.static import static
# from board.views import home


# localhost:8000으로 왔을때 board로 연결하기 위해 views의 home을 import
urlpatterns = [
    path('',include('common.urls')), #왜 여기 myboard/urls.py에서 작성하는 이유? board/urls.py와의 차이
    path("admin/", admin.site.urls),
    path("board/", include('board.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

projects/myboard/board/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User #우리 테이블(mydb)에 있는 auth_user과 매핑되는 import
# Create your models here.

class Board(models.Model):
    # 번호는 pk 설정 안하면 장고가 자동으로 id 부여해줌
    ### 필드와 필드 사이에 컴마 금지 ###
    title = models.CharField(max_length=100) #제목
    content = models.TextField(null = False,blank=False) #내용
    # writer = models.CharField(max_length=10) #글쓴이
    input_date = models.DateTimeField(default = timezone.now) #작성일
    view_count = models.IntegerField(default = 0) # 조회수

    #db에는 필드이름 _기본키이름으로 열이 생성됨
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    # 파일첨부 관련 필드
    attached_file =models.FileField(upload_to='board/%Y-%m-%d/', null = True)
    original_file_name = models.CharField(max_length=260,null = True)
    # java의 to_string과 비슷함 객체정보를 문자열로 돌려줌
    def __str__(self):
        return f'{self.id} ~ {self.title}~'

class Reply(models.Model):
    # pk : 장고가 알아서 만들어 줄것임
    # 게시글 번호(fk)
    board_obj = models.ForeignKey(Board, on_delete=models.CASCADE)
    # 사용자(fk)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # 댓글 내용
    reply_content = models.TextField(null=False,blank=False)
    # 작성 시간
    input_date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.reply_content

projects/myboard/board/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse,FileResponse
from django.template import loader
from django.core.paginator import Paginator
from django.core import serializers
from django.contrib.auth.decorators import login_required

from django.views.generic import ListView,DetailView

from json import loads
from .models import Board ,Reply

# Create your views here.

def index(request):

    result = None # 필터링 된 리스트
    context = {}
    if 'searchType' in request.GET and 'searchWord' in request.GET:
        search_type = request.GET['searchType'] # get안의 문자열은
        search_word = request.GET['searchWord'] # html의 name속성과 일치해야함
        print("searchType :{}, search_word : {}".format(search_type,search_word))

        #match:java의 switch와 비슷함
        match search_type:
            case 'title': # 검색 기준이 제목일때
                result = Board.objects.filter(title__contains = search_word)
            case 'writer': # 검색 기준이 제목일때
                result = Board.objects.filter(writer__contains = search_word)
            case 'content': # 검색 기준이 제목일때
                result = Board.objects.filter(content__contains = search_word)
        # 검색을 했을 때만 검색 기준과 키워드를 context에 넣는다
        context['searchType'] = search_type
        context['searchWord'] = search_word
    else: # QueryDict에 검색 조건과 키워드가 없을 때
        result = Board.objects.all()
    result = result.order_by("-id")
    paginator = Paginator(result,10)
    page_obj = paginator.get_page(request.GET.get('page'))
    context['page_obj'] = page_obj
    return render(request,'board/index.html', context)

def read(request,id):
    print("read실행")
    # board = Board.objects.all()
    board = Board.objects.get(id = id)

    board.view_count += 1
    board.save()
    context ={
        'board':board #애하고 fk걸려있는 쿼리 셋이 같이 딸려감
        # ',replyList':reply_list
    }
    return render(request,'board/read.html', context)
    # return render(request,'board/board.html', context)

def home(request):
    # 목록으로
    return HttpResponseRedirect("/board/")

# 내가 따로 만든 로그인 url이 있다면 login_url 키워드 변수를 지정해야한다.
@login_required(login_url='common:login')
def write(request):
    if request.method =='GET': #요청방식이 get 방식이면 화면 표시
        return render(request,'board/board_form.html')
    else: # 요청방식이 POST일때 할일
        print(request.POST)
        print(request.FILES)
        # 폼의 데이터를 DB에 저장
        title = request.POST['title']
        # writer = request.POST['writer'] #??
        content = request.POST['content']
        author = request.user # 요청에 들어있는 user객체

        board =  Board(
            title = title,
            author = author, # user객체 저장
            content = content
        )
        # get메소드 사용하는 ㅣ융
        # 딕셔너리에서 존재하지 않는 키를 딕셔너리 [킬]
        # 딕셔너리.get("키") ->None
        if request.FILES.get("uploadFile"):
            upload_file = request.FILES['uploadFile']
            # 요청에 들어있던 첨부파일을 모델에 설정
            board.attached_file = upload_file
            board.original_file_name = upload_file.name
        board.save()
        return HttpResponseRedirect('/board/')


# 글 수정
@login_required(login_url='common:login')
def update(request, id):
    board = Board.objects.get(id = id)

    # 로그인 정보가 맞지 않을 때
    if board.author.username != request.user.username:
        return HttpResponseRedirect('/board/')

    if request.method == 'GET':
        context = {'board' : board }
        return render(request , 'board/board_update.html', context)
    else:
        board.title = request.POST['title']
        # board.writer = request.POST['writer']
        board.content = request.POST['content']

        #첨부 파일이 있다면
        if request.FILES.get("uploadFile"):
            upload_file = request.FILES["uploadFile"]
            #요청에 들어있던 첨부파일을 모델에 설정
            board.attached_file = upload_file
            board.original_file_name = upload_file.name
        else: #첨부파일이 없다면
            board.attached_file=None
            board.original_file_name=None
        board.save() # save를 해야 DB에 반영됨!!!

        # 수정 후에 해당 글로 다시 이동
        redirect_url  = '/board/' + str(id) + '/'
        return HttpResponseRedirect(redirect_url)

@login_required(login_url='common:login')
def delete(request,id):
    print("id :",id)
    # 해당 객체를 가져옴
    board = Board.objects.get(id=id)

    # 글 작성자의 id와 접속한 사람의 id가 같을때
    if board.author.username == request.user.username:
        board.delete()
    return HttpResponseRedirect('/board/')


def write_reply(request,id):
    print(request.POST)

    user = request.user # 어떻게
    print("user:",user)
    reply =  loads(request.body) #요청의 body를 해석
    print("reply:",reply)

    reply_text = reply['replyText']
    board = Board.objects.get(id = id)
    board.reply_set.create(
        reply_content = reply_text,
        user = user
    )
    return JsonResponse({'result':'success'})

def load_reply(request,id):
    reply_list  = Board.objects.get(id = id).reply_set.all()
    reply_dict_list = []

    #reply_list의 정보를 가지고 dictionary 만들기
    for reply in reply_list:
        reply_dict = {
            'id' : reply.id,
            'username' : reply.user.username,
            'replyText':reply.reply_content,
            'inputDate' :reply.input_date
        }
        reply_dict_list.append(reply_dict)
    context = {'replyList':reply_dict_list}
    return JsonResponse(context)

def update_reply(request,id):
    if request.method =='GET':
        board = Board.objects.get(id=id)
        rid = request.GET['rid']
        replyText = board.reply_set.get(id=rid) #reply_set.get다시 공부할 것
        context ={
            #rid에 해당하는 reply 객체의 id하고 replyText
            'rid':rid,
            'replyText':replyText.reply_content
        }
        print(type(context))
        return JsonResponse(context)
    else:
        print("post로 받았음")

        request_body = loads(request.body)
        rid = request_body['rid']
        reply_text = request_body['replyText']
        reply = Board.objects.get(id=id).reply_set.get(id=rid)
        reply.reply_content = reply_text
        reply.save()
        return JsonResponse("",safe=False)

def delete_reply(request,id):
    request_board = loads(request.body)
    rid = request_board['rid']
    Board.objects.get(id=id).reply_set.get(id=rid).delete()
    return JsonResponse("",safe=False) #딕셔너리 형식으로 보내줘야함

def download(request,id):
    print(id)
    board = Board.objects.get(id=id)
    attached_file = board.attached_file
    original_file_name = board.original_file_name

    # 글 번호에 달려있던 첨부파일로 파일형식 응답 객체 생성
    response = FileResponse(attached_file)
    response['Content-Disposition'] = 'attachment; filename =%s'%original_file_name # 이 응답은 이런 컨텐츠 입니다.

    return response

### Class Based View ###
class BoardList(ListView): #상속받을 클래스를 적어주는데 ListView는 장고에서 제공하는 목록을 보여주는 기능
    # model = 이 페이지에서 표시할 객체 타입
    model = Board
    #오더링 속성에서는 문자열로 정렬하고싶은 열 이름을 쓴다 내림차순(-), 오름차순 정렬가능
    ordering = '-id'
    # 클래스 기반 뷰에서 사용하는 템플릿은
    # 일반적으로 이름이 객체이.html

class BoardDetail(DetailView):
    model = Board
    # def get_object(self):
    #     object = get(Board, id=self.kwargs['id'])
    #     return object
    def get(self, request, *args, **kwargs):
        self.kwargs['pk'] = self.kwargs.pop('id')
        return super().get(request, *args, **kwargs)
    #Template_name 속성 : 내가 별도로 이용하고 싶은 템플릿 파일이 있을때 해당 파일 이름 지정
    # Template_name속성을 사용하지 않으면 model이름 _detail.html을 찾아간다.
    template_name = "board/read.html"

projects/myboard/templates/board/board_form.html
{%extends 'common/base.html'%}
{%block title%}[글 쓰기]{%endblock title%}
{%block body%}
  <h1>[글쓰기]</h1>
  <!--상위 디렉토리로 이동한 후에 write/호출-->
  <form action="{%url 'board:write' %}" method="POST" enctype="multipart/form-data" onsubmit="return validate()">
    {% csrf_token %}
    <!--로그인 성공 후 이동할 url-->
    <input type="hidden" name="next" value="/board/">
    <table>
      <tr>
        <th>제목</th>
        <td><input type="text" id="title" name='title'/></td>
      </tr>
      <!--session에 writer가 없으면 해당 tr표시-->
      <!-- {% if not request.session.writer %} <tr> <th>글쓴이</th> <td><input type="text" name="writer" /></td> </tr> {%endif%} -->

      <tr>
        <th>내용</th>
        <td>
          <textarea id="content" name='content'></textarea>
        </td>
      </tr>
      <tr>
        <th>파일첨부</th>
        <!--파일 첨부-->
        <!--파일 확인-->
        <td><input type="file" name="uploadFile"></td>
      </tr>
      <tr>
        <th colspan="2"><input type="submit" value="글쓰기"/></th>
      </tr>
    </table>
  </form>
{%endblock body%}

projects/myboard/templates/board/board_list.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>

  <body>
    <h1>CBV로 객체 가져오기
    </h1>
    <!--클래스 기반에서는 기본적으로 리스트 이름을 객체이름_list로 사용가능-->
    {% for board in board_list%}
      <a href="{{board.id}}/">
        <span>{{board.id}}{{board.title}}</span><br>
      </a>
      {%endfor%}
    </body>

  </html>

projects/myboard/templates/board/board_update.html
{%extends 'common/base.html'%}
{%block title%}[글 수정하기]{%endblock title%}
{%block body%}
  <script>
    function validateFile() {
      let file = document.getElementById("uploadFile");
      console.log("파일값은", file.value);
      // 첨부파일이 원래는 있었는데 수정하면서 없을 때
      if ('{{board.original_file_name}}' !== "" && file.value === '') {
        let go = confirm("파일이 첨부되지 않았습니다. 계속하시곘습니까?")
        if (go == true) {
          return true;
        } else {
          return false;
        }
      }
    }
  </script>
  <h1>[글수정하기]</h1>
  <!--상위 디렉토리로 이동한 후에 write/호출-->
  <form action="{%url 'board:update' board.id%}" method="POST" enctype="multipart/form-data" onsubmit="return validate()">
    {% csrf_token %}
    <table>
      <tr>
        <th>제목</th>
        <td><input type="text" name="title" value="{{board.title}}" id="title"/></td>
      </tr>
      <!--session에 writer가 없으면 해당 tr표시-->
      <!-- <tr> <th>글쓴이</th> <td><input type="text" name="writer" value="{{board.writer}}" /></td> </tr> -->
      <tr>
        <th>첨부파일</th>
        <td>
          현재 첨부파일:
          {% if board.original_file_name %}
            {{board.original_file_name}}
          {% else %}
            없음
          {% endif %}
          <br>
          <input type="file" name="uploadFile" id="uploadFile" value="{{board.original_file_name}}">
        </td>
      </tr>
      <tr>
        <th>내용</th>
        <td>
          <textarea name="content" id="content">{{board.content}}</textarea>
        </td>
      </tr>
      <tr>
        <th colspan="2"><input type="submit" value="수정하기"/></th>
      </tr>
    </table>
  </form>
{%endblock body%}

projects/myboard/templates/board/index.html
{# common/base.html을 상속받겠음#}
{%extends 'common/base.html'%}
{%block title%}[게시판]{%endblock title%}

{%block body%}
  <script>
    $(document).ready(function () {
      console.log('index들어감')
    })

    function callFunction() {
      let data = {
        'txt': 'hello'
      };
      // AJAX로 서버와 통신을 할 때에도 csrf_token은 있어야한다
      $.ajax({
        url: '/board/callAjax/',
        headers: {
          'X-CSRFTOKEN': '{{csrf_token}}'
        },
        type: 'post',
        // JSON
        data: JSON.stringify(data), //JS객체를 문자열화
        success: function (res) {
          console.log(res);
          console.log(res.result); // res 객체에 들어있는 result라는 필드
          console.log("성공했음");
        }
      })
    }
  </script>
  <h1>게시판</h1>
  <table>
    {%if page_obj%}
      <tr>
        <th>#</th>
        <th>제목</th>
        <th>글쓴이</th>
        <th>작성일</th>
        <th>조회수</th>
      </tr>
      {% for board in page_obj %}
        <tr>
          <td>{{board.id}}</td>
          <!--파라미터가 있는 주소를 호출할 때 -->
          <!--name 뒤에 한칸 띄우고 파라미터의 값 지정-->
          <td>
            <a href="{%url 'board:detail' board.id%}">{{board.title}}&nbsp<span style = " font-size:0.8em;  color: green;">[{{board.reply_set.all.count}}]</span></a>
            {%if board.original_file_name%}
            <img src="/static/attach-file.png" style="width:20px; height:20px; ">
            {%endif%}
          </td>
          <td>{{board.author}}
            {{board.author_id}}
          </td>
          <!--{{board.author.username}}과 {{board.author}}같음-->
          <td>{{board.input_date}}</td>
          <td style="text-align: center;">{{board.view_count}}</td>
        </tr>
      {% endfor %}
    </table>
    {%else%}
    <p>게시물이 존재하지 않습니다.</p>
    {%endif%}
    <form>
      <select name="searchType">
        {% if searchType == 'title'%}
          <option value="title" selected="selected">제목</option>
        {% else %}
          <option value="title">제목</option>
        {% endif %}
        {% if searchType == 'writer'%}
          <option value="writer" selected="selected">글쓴이</option>
        {% else %}
          <option value="writer">글쓴이</option>
        {% endif %}
        {% if searchType == 'content'%}
          <option value="content" selected="selected">내용</option>
        {% else %}
          <option value="content">내용</option>
        {% endif %}
      </select>
      <input type="text" name="searchWord" value="{{searchWord}}"/>
      <input type="submit" value="검색"/>
    </form>
    {% if page_obj.has_previous %}
    <!--GET의 parameter(쿼리스트링)은 url의 구성요소와 별도로 표시-->
      <a href="{%url 'board:index' %}?page=1">&laquo;</a> <!--이거 바꾸는 이유가 뭐임-->
      <a href="{%url 'board:index' %}?page={{page_obj.previous_page_number}}">이전</a> <!--이것도 바꾸는 이유가..?-->
    {% endif %}
    <!--page_obj.number 는 현재 페이지 번호를 의미-->
    <!--num_pages는 전체 페이지 수(paginator로 지정한 보여줄 게시물 수로 나눈 페이지)-->
    <!-- {{page_obj.number}} of {{page_obj.paginator.num_pages}} -->
    [
    {%for page_number in page_obj.paginator.page_range%}
      {%if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5%}
        {%if searchWord%}
          <a href="?page={{page_number}}&searchType={{searchType}}&searchWord={{searchWord}}">{{page_number}}</a>
          {%else%}
          {% if page_number == page_obj.number %}
            <a href="?page={{page_number}}" class="current">{{page_number}}</a>
            &nbsp;
            {%else%}
            <a href="?page={{page_number}}">{{page_number}}</a>
            &nbsp;
            {%endif%}
            {%endif%}
            {%endif%}
            {%endfor%}
            ]
            {%if page_obj.has_next%}
              <a href="{%url 'board:index' %}?page={{page_obj.next_page_number}}">다음</a>
              <a href="{%url 'board:index' %}?page={{page_obj.paginator.num_pages}}">
                &raquo;</a>
            {% endif %}<br/>

            <!--페이징 2 : 가지고 있는 페이지의 번호 다 보여주기-->
            <!-- {%for page_number in page_obj.paginator.page_range %} <a href="{%url 'board:index' %}?page={{page_number}}" >{{page_number}}</a> &nbsp; {%endfor%} <br> -->
            <!--페이징 3: 2를 개선한 버전-->
            <!-- {%for page_number in page_obj.paginator.page_range%} {%if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5%} <a href="{%url 'board:index' %}?page={{page_number}}">{{page_number}}</a> &nbsp; {%endif%} {%endfor%} -->
            <br>
            {%if user.is_authenticated%}
              <a href="{%url 'board:write'%}">글쓰기</a>
              {%endif%}
              {% comment %} <input type="button" value="눌러보세요" onclick="callFunction();"> {% endcomment %}
              <div id="result"></div>
            {%endblock body%}

projects/myboard/templates/board/read.html
{%extends 'common/base.html'%}
{%block title%}[글보기]{%endblock title%}
{%block body%}

  <script>
    $(document).ready(function () {
      //1.수정 폼 숨기기
      $('#updateForm').hide();
      //2.버튼에 이벤트 달기
      /*$('#btnWrite').click(function () {
          writeReply();
        })
        $('#btnUpdate').click(function () {
          updateReply();
        })*/
      // loadReplyList();
      loadreply();
    });

    function showUpdateForm(param) {
      // location.href = 'update_reply?rid=' + param
      $('#writeForm').hide()
      $('#updateForm').show()
      $.ajax({
        url: '{%url "board:update_reply" id=board.id%}',
        type: 'get',
        data: {
          'rid': param
        },
        success: function (res) {
          //1. 수정 입력창에 댓글 내용 표시
          $("#replyTextUpdate").val(res.replyText);
          //2. rid라는 id를 가진 hidden 태그에 값 설정
          $("#rid").val(res.rid);
        },
        error: function () {
          alert("안갔음 ㅅㄱ ㅋㅋ");
        }
      })
    }

    function updateReply() {
      let replyText = $('#replyTextUpdate').val();
      let rid = $('#rid').val();
      let data = {
        "replyText": replyText,
        "rid": rid
      };
      $.ajax({
        url: '{%url "board:update_reply" id=board.id%}',
        type: 'post',
        headers: {
          'X-CSRFTOKEN': '{{csrf_token}}'
        },
        data: JSON.stringify(data),
        // data: {
        //   'rid': rid,
        //   'replyText': replyText
        // },
        success: function () {
          loadreply();
          $('#updateForm').hide();
          $("#writeForm").show();
        }
      })
    }

    function loadreply() {
      $.ajax({
        url: '{% url "board:load_reply" id=board.id %}',
        type: 'get',
        success: function (res) {
          // console.log(res);
          let str = "<table style='width: 500px;'>";
          console.log("댓글의 갯수", res.replyList.length);
          if (res.replyList.length == 0) {
            alert("댓글 없음");
          }
          $.each(res.replyList, function (index, item) {
            let replacedDate = item
              .inputDate
              .replace("T", " ")
              .replace("Z", " ")
              .split(".")[0]
            str += "<tr>";
            str += "<td>" + item.replyText + "</td>";
            str += "<td style='text-align:center;'>" + item.username + "</td>";
            str += "<td style='width: 150px;'>" + replacedDate + "</td>";
            str += "<td style='width: 80px; text-align: center;'>";
            if ('{{user.username}}' === item.username) {
              str += "<a href = '#' onclick = 'showUpdateForm(" + item.id + ")'>수정</a>/";
              str += "<a href = '#' onclick = 'deleteReply(" + item.id + ")'>삭제</a>"
            }
            str += "</td>";
            str += "</tr>";

          });

          str += "</table>";

          $('#replyList').html(str);
        }
      })
    }

    function writeReply() {
      // let id = '{{board.id}}';
      replyText = $('#replyTextWrite').val();
      let data = {
        "replyText": replyText
      };
      $.ajax({
        url: '{% url "board:write_reply" id=board.id %}',
        type: 'post',
        data: JSON.stringify(data),
        headers: {
          'X-CSRFTOKEN': '{{csrf_token}}'
        },
        success: function (res) {
          $('#replyTextWrite').val("");
          loadreply();
        },
        error: function () {
          console.log("에러뜸")
        }
      })
    }

    function deleteReply(rid) {
      //location.href='../{{board.id}}/delete_reply/' + data; 난 사실 잘 몰루..
      let data = {
        'rid': rid
      }
      $.ajax({
        url: '{%url "board:delete_reply" id=board.id%}',
        type: 'post',
        headers: {
          'X-CSRFTOKEN': '{{csrf_token}}'
        },
        data: JSON.stringify(data),
        success: function (data) {
          loadreply();
        }
      });
    }
  </script>
  <h1>#{{board.id}}</h1>
  <table>
    <tr>
      <th>제목</th>
      <th>내용</th>
      <th>작성자</th>
      <th>조회수</th>
      <th>첨부파일</th>
    </tr>
    <tr>
      <td>{{board.title}}</td>
      <td>{{board.content}}</td>
      <td>{{board.author.username}}</td>
      <td>{{board.view_count}}</td>
      {%if board.original_file_name%}
        <td colspan='3'>
          <!--/board/0/download/-->
          <a href="{%url 'board:download' id=board.id %}">{{board.original_file_name}}</a>
        </td>
        {%endif%}
      </tr>
    </table>
    <br><br><br>
    <!--수정/삭제-->
    {%if board.author.username == user.username %}
      <br/>
      <a href="{%url 'board:update' board.id%}">수정</a>&nbsp;
      <a href="{%url 'board:delete' board.id%}" onclick="return confirm('정말 삭제 하시겠습니까?')">삭제</a>&nbsp;
      {%endif%}
      <hr>
      <div id="replyArea">
        <!--댓글 목록 표시할 곳-->
        <div id="replyList"></div>
        <!--댓글 입력 폼-->
        <div id="replyForm">
          <div id="writeForm">
            <!--글쓰기 폼-->
            <textarea name="reply_text" id="replyTextWrite" cols="30" rows="1.5"></textarea>
            <input type="button" id="btnWrite" value="댓글쓰기" onclick="return validateReply(this)">
          </div>
          <div id="updateForm">
            <!--글 수정 폼-->
            <input type="hidden" name="rid" id="rid">
            <textarea name="reply_text" id="replyTextUpdate" cols="30" rows="1.5"></textarea>
            <input type="button" id="btnUpdate" value="댓글수정" onclick="return validateReply(this)">
          </div>
        </div>
      </div>
      <br/>
      <a href="../">목록으로</a>
    {%endblock body%}