projects/shop/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path('',views.index,name='index'),
    path('add_item/',views.add_item, name='add_item'),
    path('item_list/',views.item_list, name='item_list'),
    path('search_item/',views.search_item),
    path('add_order/',views.add_order, name = "add_order"),
    path('<int:id>/update_item/',views.update_item, name = "update_item"),
    path('<int:id>/delete_item/',views.delete_item, name ="delete_item"),
    
    path('cbv/', views.OrderList.as_view(),name = "cbv"),
]

projects/shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("",include('item.urls')),
    path("admin/", admin.site.urls),
    path("item/",include('item.urls')),
]

projects/shop/item/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Item(models.Model):
    item_name =models.CharField(max_length=100)
    item_count=models.IntegerField(null=False,default=1)

class Order(models.Model):
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    orderdate = models.DateTimeField(default = timezone.now)
    quantity = models.IntegerField(null=False)

projects/shop/item/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse,FileResponse
from .models import Item,Order
from django.views.generic import ListView,DetailView
# Create your views here.
def index(request):
    return render(request,'item/index.html')

# 상품 추가해주는 함수
def add_item(request):
    if request.method=="POST":
        item_name = request.POST['item_name']
        item_count = request.POST['item_count']
        item =  Item(
            item_name = item_name,
            item_count = item_count # user객체 저장
        )
        item.save()
        return HttpResponseRedirect('/item/')
    else:
        return render(request,'item/add_item.html')
    

# 상품 검색
def search_item(request):
    item_name = request.GET['item_name']
    # 상품 이름을 포함하는 검색
    result = Item.objects.filter(item_name__contains = item_name)
    result = result.order_by("-id")
    return render(request,'item/item_list.html', {'item_list':result})

# 주문 추가
def add_order(request):
    if request.method =="POST":
        # 주문 수량을 가져온다
        item_quantity = request.POST['quantity']
        item = Item.objects.get(id=request.POST['opt_id'])
        order = Order(
            item = item,
            quantity = item_quantity
        )
        order.save()
        return HttpResponseRedirect("/item/")
        
    # get 방식으로 item리스트를 모두 받아옴    
    else:
        item_list = Item.objects.all()
        if request.GET:
            id = request.GET['id']
            item = Item.objects.get(id = id)
            item_count = item.item_count
            return JsonResponse({"item_count":item_count})
        #  아이템을 담아서 쏴줌
        return render(request,"item/add_order.html",{'item_list': item_list})
    
def update_item(request,id):
    if request.method =="POST":
        print("id =",id)
        print(request.POST['item_name'])
        print(request.POST['item_count'])
        item  = Item.objects.get(id=id)
        item.item_name=request.POST['item_name']
        item.item_count=request.POST['item_count']
        item.save()
        return HttpResponseRedirect('/item/item_list/')
    else:
        print("id:",id)
        item = Item.objects.get(id = id)
        return render(request,"item/update_item.html",{'item': item})

def delete_item(request,id):
    Item.objects.get(id=id).delete()
    return HttpResponseRedirect('/item/item_list/')

class OrderList(ListView):
    model = Order
    ordering = '-id'
    
# 상품 리스트 보내주는 함수
def item_list(request):
    item_list = Item.objects.all().order_by("-id")
    # 모든 상품을 item_list로 보내줌
    return render(request,'item/item_list.html', {'item_list':item_list})

projects/shop/templates/item/addItem.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>[상품등록 시스템]</title>
  </head>

  <body>
    <h1>상품등록 시스템</h1>
    <form action="{%url 'item:addItem' %}" method="POST">
      {% csrf_token %}
      <table border="1">
        <tr>
          <th>상품명</th>
          <td><input type="text" name="item_name" id="item_name"></td>
        </tr>
        <tr>
          <th>수량</th>
          <td><input type="number" name="item_count" id="item_count"></td>
        </tr>
        <tr>
          <th colspan="3">
            <input type="submit" value="상품등록">
          </th>
        </tr>
      </table>
    </form>

  </body>

</html>

projects/shop/templates/item/addOrder.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script>
      function chageSelect() {
        let item_id= document.getElementById("optid").value;
        console.log("제품 수량:", item_id);
       $.ajax({
        url:'{%url "item:addOrder"%}',
        type:'GET',
        data:{'id' : item_id},
        success:function(res){
          item_count=res.item_count
          $('#itemCount').val(item_count)
        }
       })
        // 상품의 아이디 값을 넣어줘야한다.
        //해당하는 아이디의 상품 재고수량을 출력한다
      }
    </script>
    <style>
      textarea {
        width: 80%;
        height: 1.25em;
        border: none;
        resize: none;
      }
    </style>
    <title>[주문 등록 페이지]</title>
  </head>
<!--주문량이 재고 넘으면 안됨, 그리고 상품 리스트에 없는 주문이 있어선 안됨-->
  <body>
    <h1>[주문 등록]</h1>
    <!--폼 액션 addOrder를 통해 정보를 보내줌-->
    <form action="{% url 'item:addOrder'%}" method="POST" >
      {% csrf_token %}
      <table border="1">
        <tr>
          <th>상품명</th>
          <td>
            <!--select를 통해서 상품 리스트의 품목들을 뽑아와서 선택한다.-->
            <select id = "optid" name ="optid" onchange="chageSelect()" style="width:200px;"> <!--onchange가 일어날때마다 changeSelect()함수 실행-->
              <!--views에서 items로 쏴준 객체-->
              {% for item in items %} <!--item을 하나씩 가져온다-->
                <option  value="{{item.id}}">{{item.item_name}}</option> <!--상품의 이름을 선택하면 option.value에 상품의 재고를 담는다-->
                <!--상품의 아이디를 가져온다 단 상품의 선택이 바뀔때마다 아이디의 값도 변경되어야 한다.-->
                {% endfor %}
            </select>
            
          </td>
          <th>남은 재고</th>
          <td>
            <textarea readonly id="itemCount" cols="5" rows="5" style=" font-size:1.5em; "></textarea>
          </td>
        </tr>
        <tr>
          <th>주문 수량</th>
          <td style="width:200px;"><input type="number" name="quantity" id="quantity" style="width:200px;"></td>
        </tr>
      </table>
      <input type="submit" value="상품등록">
    </form>
  </body>

</html>

projects/shop/templates/item/add_item.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>[상품등록 시스템]</title>
  </head>

  <body>
    <h1>상품등록 시스템</h1>
    <form action="{%url 'item:add_item' %}" method="POST">
      {% csrf_token %}
      <table border="1">
        <tr>
          <th>상품명</th>
          <td><input type="text" name="item_name" id="item_name"></td>
        </tr>
        <tr>
          <th>수량</th>
          <td><input type="number" name="item_count" id="item_count"></td>
        </tr>
        <tr>
          <th colspan="3">
            <input type="submit" value="상품등록">
          </th>
        </tr>
      </table>
    </form>
    <a href="../">뒤로</a>
  </body>

</html>

projects/shop/templates/item/add_order.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function(){
        chageSelect()
      });
      function chageSelect() {
        let item_id= document.getElementById("opt_id").value;
        console.log("제품 수량:", item_id);
       $.ajax({
        url:'{%url "item:add_order"%}',
        type:'GET',
        data:{'id' : item_id},
        success:function(res){
          item_count=res.item_count
          $('#itemCount').val(item_count)
        }
       })
        // 상품의 아이디 값을 넣어줘야한다.
        //해당하는 아이디의 상품 재고수량을 출력한다
      }
    </script>
    <style>
      textarea {
        width: 80%;
        height: 1.25em;
        border: none;
        resize: none;
      }
    </style>
    <title>[주문 등록 페이지]</title>
  </head>
<!--주문량이 재고 넘으면 안됨, 그리고 상품 리스트에 없는 주문이 있어선 안됨-->
  <body>
    <h1>[주문 등록]</h1>
    <!--폼 액션 addOrder를 통해 정보를 보내줌-->
    <form action="{% url 'item:add_order'%}" method="POST" >
      {% csrf_token %}
      <table border="1">
        <tr>
          <th>상품명</th>
          <td>
            <!--select를 통해서 상품 리스트의 품목들을 뽑아와서 선택한다.-->
            <select id = "opt_id" name ="opt_id" onchange="chageSelect()" style="width:200px;"> <!--onchange가 일어날때마다 changeSelect()함수 실행-->
              <!--views에서 items로 쏴준 객체-->
              {% for item in items %} <!--item을 하나씩 가져온다-->
                <option  value="{{item.id}}">{{item.item_name}}</option> <!--상품의 이름을 선택하면 option.value에 상품의 재고를 담는다-->
                <!--상품의 아이디를 가져온다 단 상품의 선택이 바뀔때마다 아이디의 값도 변경되어야 한다.-->
                {% endfor %}
            </select>
            
          </td>
          <th>남은 재고</th>
          <td>
            <textarea readonly id="itemCount" cols="5" rows="5" style=" font-size:1.5em; "></textarea>
          </td>
        </tr>
        <tr>
          <th>주문 수량</th>
          <td style="width:200px;"><input type="number" name="quantity" id="quantity" style="width:200px;"></td>
        </tr>
      </table>
      <input type="submit" value="상품등록">
    </form>
    <a href="../">뒤로</a>
  </body>

</html>

projects/shop/templates/item/index.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>[상품 관리 시스템]</title>
  </head>

  <body>
    <h1>[상품 관리 시스템]</h1>
    <ul>
      <li>
        <a href="{%url 'item:add_item' %}">상품 등록</a>
      </li>
      <li>
        <a href="{%url 'item:item_list' %}">상품목록 조회</a>
      </li>
      <li>
        <a href="{%url 'item:add_order' %}">주문정보 등록</a>
      </li>
      <li>
        <a href="cbv/">주문정보 조회</a>
      </li>
      <li>
        <a href="">상품별 판매량 조회</a>
      </li>
    </ul>
  </body>
<!--
  일단 상품별 판매량 조회
  1. 상품을 전부 보여줌
  2. 동일 상품의 주문 수량을 모두 더함
  3. 주문 수량으로 정렬해서 출력 
  이건 내일의 나 화이팅 -->
</html>

projects/shop/templates/item/itemList.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>[상품 목록]</title>
  </head>

  <body>
    <h1>[상품 목록]</h1>
    <table border="1">
      {%if item_list%}
        <tr>
          <th>#</th>
          <th>제목</th>
          <th>수량</th>
          <th>수정삭제</th>
        </tr>
        {% for item in item_list %}
          <tr>
            <td>{{item.id}}</td>
            <td>
              <a>{{item.item_name}}</a>
            </td>
            <td style="text-align: center;">{{item.item_count}}</td>
            <td><a href="{%url 'item:update_item' id=item.id%}">수정</a> / <a href="{%url 'item:delete_item' id=item.id%}">삭제</a></td>
          </tr>
        {% endfor %}
      </table>
      {%else%}
      <p>게시물이 존재하지 않습니다.</p>
      {%endif%}

      <form action="../searchItem/">
        <p>상품정보 검색</p>
        <input type="text" name="item_name"/>
        <input type="submit" value="검색"/>
      </form>
    </body>

  </html>

projects/shop/templates/item/item_list.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>[상품 목록]</title>
  </head>

  <body>
    <h1>[상품 목록]</h1>
    <table border="1">
      {%if item_list%}
        <tr>
          <th>#</th>
          <th>제목</th>
          <th>수량</th>
          <th>수정삭제</th>
        </tr>
        {% for item in item_list %}
          <tr>
            <td>{{item.id}}</td>
            <td>
              <a>{{item.item_name}}</a>
            </td>
            <td style="text-align: center;">{{item.item_count}}</td>
            <td><a href="{%url 'item:update_item' id=item.id%}">수정</a> / <a href="{%url 'item:delete_item' id=item.id%}">삭제</a></td>
          </tr>
        {% endfor %}
      </table>
      {%else%}
      <p>게시물이 존재하지 않습니다.</p>
      {%endif%}

      <form action="../search_item/">
        <p>상품정보 검색</p>
        <input type="text" name="item_name"/>
        <input type="submit" value="검색"/>
      </form>
    </body>
    <a href="../">뒤로</a>
  </html>

projects/shop/templates/item/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>주문 명세서</h1>
    <table border ="1">
        <tr>
            <th>주문 제품</th>
            <th>주문 날짜</th>
            <th>주문 수량</th>
        </tr>
    {%for order in order_list%}
        <tr>
            <th>{{order.item.item_name}}</th>
            <th>{{order.orderdate}}</th>
            <th>{{order.quantity}}</th>
        </tr>
    {%endfor%}
    </table>
    <a href="../">뒤로</a>
</body>
</html>

projects/shop/templates/item/updateItem.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>[상품수정 시스템]</title>
  </head>

  <body>
    <!-- {{items.id}} -->
    <h1>상품수정 시스템</h1>
    <form action="{%url 'item:update_item' id=items.id %}" method="POST">
      {% csrf_token %}
      <table border="1">
        <tr>
          <th>상품명</th>
          <td>
            <input
              type="text"
              name="item_name"
              id="item_name"
              value="{{items.item_name}}"
            />
          </td>
        </tr>
        <tr>
          <th>수량</th>
          <td>
            <input
              type="number"
              name="item_count"
              id="item_count"
              value="{{items.item_count}}"
            />
          </td>
        </tr>
        <tr>
          <th colspan="3">
            <input type="submit" value="상품등록" />
          </th>
        </tr>
      </table>
    </form>
  </body>
</html>

projects/shop/templates/item/update_item.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>[상품수정 시스템]</title>
  </head>

  <body>
    <!-- {{items.id}} -->
    <h1>상품수정 시스템</h1>
    <form action="{%url 'item:update_item' id=item.id %}" method="POST">
      {% csrf_token %}
      <table border="1">
        <tr>
          <th>상품명</th>
          <td>
            <input
              type="text"
              name="item_name"
              id="item_name"
              value="{{item.item_name}}"
            />
          </td>
        </tr>
        <tr>
          <th>수량</th>
          <td>
            <input
              type="number"
              name="item_count"
              id="item_count"
              value="{{item.item_count}}"
            />
          </td>
        </tr>
        <tr>
          <th colspan="3">
            <input type="submit" value="상품등록" />
          </th>
        </tr>
      </table>
    </form>
    <a href="../">뒤로</a>
  </body>
</html>