projects/myboard/board/urls.py
from django.urls import path
from . import views

app_name ='board'

#여기는 board에 있는 urls.py다
urlpatterns = [

    # .../board
    path('', views.index, name = 'index'),
    # 글읽기 주소 /board/0
    path('<int:id>/',views.read, name='detail'),
    # 글쓰기 주소
    path('write/',views.write, name='write'),
    # 수정 주소
    path('<int:id>/update/',views.update, name ='update'),
    # 삭제 주소
    path('<int:id>/delete/',views.delete, name ='delete'),

    # #AJAX
    # path('callAjax/',views.call_ajax),
    # 댓글 쓰기 주소
    path('<int:id>/write_reply/',views.write_reply, name = "write_reply"),
    # 댓글 수정 주소
    path('<int:id>/update_reply/',views.update_reply, name = "update_reply"),
    # 댓글 로딩 주소
    path('<int:id>/load_reply/',views.load_reply, name = 'load_reply'),
    # 댓글 삭제 주소
    path('<int:id>/delete_reply/',views.delete_reply, name = "delete_reply"),
    path("<int:id>/download/",views.download, name = "download"),

    # CBV방식으로 호출할 주소 cbv라는 글자가 붙어있으면 호출
    # as_view : 클래스를 view의 기능으로 사용하겠다.
    path('cbv/', views.BoardList.as_view()),
    path('cbv/<int:id>/', views.BoardDetail.as_view()),
]

projects/myboard/common/urls.py
# common/urls.py
from django.urls import path 

# settings.py에 기본으로 있음 로그인 관련
from django.contrib.auth import views as auth_view
# from. =현재폴더에서 
# 현재폴더에서 views.py를 가지고오는데 그ㅇ름이 common_view다
from . import views as common_view

app_name= 'common'

urlpatterns=[
    path('',common_view.index, name='index'),
    # 로그인
    path('login/',auth_view.LoginView.as_view(template_name ='common/login.html'), name= 'login'),
    # 로그아웃
    path('logout/',auth_view.LogoutView.as_view(), name = 'logout'),
    # 회원 가입
    path('signup/',common_view.signup_custom,name = 'signup'),
    # 회원 삭제
    path('delete/',common_view.delete, name ='delete'),
    # 회원 수정
    path('update/',common_view.update, name ='update'),
    
    path('mypage/',common_view.mypage, name ='mypage'),

    # 회원가입 v1
    # path('signup/',common_view.signup),
    
]

projects/myboard/myboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings #현재 프로젝트의 settings.py를 의미
from django.conf.urls.static import static
# from board.views import home


# localhost:8000으로 왔을때 board로 연결하기 위해 views의 home을 import
urlpatterns = [
    path('',include('common.urls')), #왜 여기 myboard/urls.py에서 작성하는 이유? board/urls.py와의 차이
    path("admin/", admin.site.urls),
    path("board/", include('board.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

projects/myboard/common/models.py
from django.db import models

# Create your models here.

projects/myboard/common/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm #유저 크리에이션 폼은 username pw1,2있는 폼
from django.contrib.auth.models import User

# UserCreationForm을 상속받는 UserForm을 작성
class UserForm(UserCreationForm):
    email = forms.EmailField(label = "이메일") # label이 뭘까용
    first_name = forms.CharField #first_name이라는 필드 생성
    last_name = forms.CharField

    class Meta : # 폼의 정보를 담고있는 클래스(내부 클래스) #내부 클래스란?
        model = User
        fields = ("username","email","first_name","last_name")

class CustomChangeForm(UserChangeForm):
    class Meta:
        model =User
        fields = ("email","first_name","last_name")

projects/myboard/common/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm ,UserChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
# 우리가 만든 custom 회원가입 form,customchangeform
from .forms import UserForm,CustomChangeForm

# Create your views here.
def index(request):
    return render(request,"common/index.html")

def signup(request):
    if request.method =="POST":
        # 요청 객체가 담고 있는 정보로 사용자 생성 폼 만든다
        print(request.POST)
        form = UserCreationForm(request.POST)
        
        if form.is_valid(): # form의 내용이 유효하다면(비어있지 않은지, pw1,2가 동일한지 이메일 형식을 따르는지)
            form.save() #db에 form정보 저장
            
            # 폼에 입력한 값 가져오기
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')

            # 사용자 인증
            user = authenticate(username=username, password=raw_password)
            # 로그인
            login(request,user)

            return redirect('/')
    else:
        print(request.GET)
        form = UserCreationForm(request.GET)
    return render(request,"common/signup.html",{'form':form})

def signup_custom(request):
    if request.method =="POST":
        print(request.POST) #QueryDict 한번 보기

        form = UserForm(request.POST) # request.POST에 담겨있는 정보를 UserForm형식으로 변환
        # form이 유효한가?(is_valid())
        if form.is_valid():
            form.save() # 폼의 내용을 DB(auth user)에 바로 저장

            # 폼의 정보를 취득
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            # 폼에있는 정보를 가져와서 인증을 시킴
            user = authenticate(username = username, password = raw_password, first_name=first_name,last_name=last_name)
            login(request, user) #사용자 인증 후 로그인 

            return redirect('/') # 로그인 하고 메인 페이지로 넘김
    else: # 요청이 get일때 
        form = UserForm() # 비어있는 새폼 만들어주기

    return render(request,'common/signup.html',{'form':form})


def delete(request):
    if request.user.is_authenticated:
        request.user.delete() # user 정보 삭제
        # render나 redirect의 파라미터로 app_name:url_name 작성 가능
        return redirect('common:index')
    
def update(request):
    if request.method =="POST":
        print("POST방식")
        form = CustomChangeForm(request.POST, instance = request.user)
        print("form>>",form)
        if form.is_valid():
            form.save() #form이 유효하다면 해당 내용 저장
            return redirect('common:index')
    else:
        print("get방식")
        form = CustomChangeForm()   
        # customchangeform(instance) 보내면 django가 보내는 form을 사용할 수 있
    return render(request,'common/update.html',{'form':form})

def update(request):
    if request.method =="POST":
        # print("POST방식")
        form = CustomChangeForm(request.POST, instance = request.user)
        # print("form>>",form)
        if form.is_valid():
            form.save() #form이 유효하다면 해당 내용 저장
            return redirect('common:index')
    else:
        # print("get방식")
        form = CustomChangeForm()   
        # customchangeform(instance) 보내면 django가 보내는 form을 사용할 수 있
    return render(request,'common/update.html',{'form':form})

def mypage(request):
    form = CustomChangeForm()
    return render(request,'common/mypage.html',{'form':form})

projects/myboard/templates/common/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css'%}"/>
    <script src="{% static 'script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <!--틀이 되는 템플릿의 title이 덮어써지지 않도록-->
    <title>
      {% block title%}{%endblock title%}
    </title>
    <script>
      function showUpdateForm(param) {
        location.href = 'update_reply?rid=' + param
      }
    </script>
    <!--block title-->
  </head>

  <body>
    <!--다른 내용을 삽입할 자리를 만들기-->
    <!--템플릿 태그에 대해 더 공부하기-->
    <!--내가 집어넣고 싶은 조각(fragment)를 include-->
    {% include 'common/menubar.html' %}
    {%block body%}{%endblock body%}
  </body>

</html>

projects/myboard/templates/common/index.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시판</title>
    <script>
      function confirmDelete() {
        let c = confirm('정말 삭제하시겠어요?')
        if (C) {
          location.href = '/delete/'
        }

      }
    </script>
  </head>

  <body>
    <h1>안녕하세요</h1>
    <!--django에서 제공하는 User모델-->
    <h2>
      Hello,
      {%if user.is_authenticated %}
        <!--user정보가 있으면 username 표시-->
        {{user.username}}
        {%else%}
        <!--없으면 그냥 GUEST표시-->
        GUEST
        {%endif%}
      </h2>

      <ul>

        {%if not user.is_authenticated %}
          <li>
            <a href="{%url 'common:signup'%}">회원가입</a>
          </li>
          <li>
            <a href="{%url 'common:login'%}">로그인</a>
          </li>
        {%elif user.is_authenticated%}
          <li>
            <a href="{%url 'common:logout'%}">로그아웃</a>
          </li>
          <li>
            <a href="{%url 'common:mypage'%}">마이페이지</a>
          </li>
          {%endif%}
          <li>
            <a href="{%url 'board:index'%}">게시판으로</a>
          </li>
          <!-- CBV 호출 -->
          <li>
            <a href="/board/cbv">게시판(CBV)</a>
          </li>
        </ul>
      </body>

    </html>

projects/myboard/templates/common/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
</head>
<body>
            <!--아이디와 비밀번호를 입력받는 폼-->
    <form action="{%url 'common:login'%}" method="post">
        {%csrf_token%}
        <!--hidden 태그 next의 value로 next를 사용하면 주소의 쿼리스트링에 있던 ?next=주소로 이동-->
        <!--특정 문자열을 용하면 해당하는 주소로 이동-->
        <input type="hidden" name = "next"  value="/board/">
        <table>
            <!--로그인의 name속성을 username과 password로 지정하면 장고 auth에서 정해진 키를 통해 넘겨줌 -->
            <tr>
                <th>아이디</th>
                <td><input type="text" name = username></a></td>
            </tr>
            <tr>
                <th>비밀번호</th>
                <td><input type="password" name = password></td>
            </tr>
            <tr>
                <th colspan="2"><input type="submit" value="로그인"></th>
            </tr>
        </table>
    </form>
</body>
</html>

projects/myboard/templates/common/menubar.html
<!--vs code 에서 . 입력하고 자동완성 하면 비어있는 div 자동완성-->
<div class="menubar">
    <table>
        <tr>    
            <!--아래의 호출법은 주소를 하드코딩하는것이 아니라 -->
            <!--urls.py에 정의된 name 속성을 통해서 이동-->
            <th><a href="/">홈</a>&nbsp;&nbsp;</th>
            {%if user.is_authenticated%}
            <th><a href="{%url 'common:logout'%}">로그아웃</a></th>
            {%else%}
            <th><a href="{%url 'common:login'%}">로그인</a></th>
            <th><a href="{%url 'common:signup'%}">회원가입</a>&nbsp;</th>
            {%endif%}
            <th><a href="{%url 'board:index' %}">게시판으로 이동</a></th>
        </tr>
    </table>
    
        
    
        
        

</div>
<div>
    {%if user.is_authenticated%}
    {{user.username}}님 안녕하세요
    {%endif%}
</div>

projects/myboard/templates/common/mypage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>내정보</title>
</head>
<body>
    <h1>{{user.username}}님의 페이지입니다.</h1>
    <form action="{%url 'common:update'%}" method="get">
        {%csrf_token%}
        <table border="1">
            <tr>
                <th>아이디</th>
                <td>{{user.username}}</td>
            </tr>
            <tr>
                <th>성</th>
                <td>{{user.last_name}}</td>
            </tr>
            <tr>
                <th>이름</th>
                <td>{{user.first_name}}</td>
            </tr>
            <tr>
                <th>
                    이메일
                </th>
                <td>{{user.email}}</td>
            </tr>
        </table>
        <input type="submit" value="정보수정하기">
    </form>
    <input type="button" value="회원정보삭제" onclick="javascript:confirmDelete()">
    <!-- <a href="#" >회원정보삭제</a> -->
</body>
</html>

projects/myboard/templates/common/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>회원가입</h1>
    <form action="../signup/" method="post">
        {%csrf_token%}
        <!--아이디-->
        <!--비밀번호 -->
        <!--비밀번호 확인-->
        <!--회원가입-->
        <table>
            <!--각 태그에 적용된 name 속성은 UserCreativeForm에서 제공하는 필드 이름과 같다.-->
            <tr>
                <th>
                    아이디
                </th>
                <td><input type="text" name = username></td>
            </tr>
            <tr>
                <th>
                    비밀번호
                </th>
                <td><input type="password" name = password1></td>
            </tr>
            <tr>
                <th>
                    비밀번호확인
                </th>
                <td><input type="password" name = password2></td>
            </tr>
            <tr>
                <th>firstname</th>
                <td><input type="text" name = "first_name"></td>
            </tr>
            <tr>
                <th>lastname</th>
                <td><input type="text" name = "last_name"></td>
            </tr>
            <tr>
                <th>이메일</th>
                <td><input type="email" name = "email"></td>
            </tr>
            <tr>
                <th colspan="2">
                    <input type="submit"value="회원가입">
                </th>
            </tr>
            </table>
    </form>
</body>
</html>

projects/myboard/templates/common/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원 정보 수정</title>
</head>
<body>
    <h1>회원 정보 수정</h1>
    <form action="{%url 'common:update'%}" method="post">
        {%csrf_token%}
        <table border="1">
            <tr>
                <th>아이디</th>
                <td>{{user.username}}</td>
            </tr>
            <tr>
                <th>성</th>
                <td><input type="text"name ="last_name" value="{{user.last_name}}"></td>
            </tr>
            <tr>
                <th>이름</th>
                <td><input type="text"name ="first_name" value="{{user.first_name}}"></td>
            </tr>
            <tr>
                <th>
                    이메일
                </th>
                <td><input type="text" name = "email" value="{{user.email}}"></td>
            </tr>
        </table>
        <input type="submit" value="정보수정">
    </form>
</body>
</html>